name = "csharp"
version = "1.0.0"
author = "sharpSteff"
display-name = "C#"
description = "C# for lapce using OmniSharp"
wasm = "bin/csharp.wasm"

[activation]
language = []
workspace-contains = []

#[config."volt.serverPath"]
#default = "OmniSharp"
#description = "Path to custom LSP executable"

# [config."volt.serverArgs"]
# default = []
# description = ""

# [config."lspSettingArray"]
# default = []
# description = ""

# [config."lspSettingString"]
# default = ""
# description = ""

# [config."lspSettingBool"]
# default = false
# description = ""
