name = "csharp"
version = "1.2.0"
author = "sharpSteff"
display-name = "C#"
description = "C# for lapce using csharp-ls"
wasm = "target/wasm32-wasi/release/lapce-plugin-csharp.wasm"
icon = "logo.png"
repository = "https://github.com/sharpSteff/lapce-csharp-plugin.git"

[activation]
language = ["csharp"]
workspace-contains = ["*/*.csx", "*/*.csproj", "*/*.sln"]

[config."volt.serverPath"]
default = ""
description = "Path to custom LSP executable"

[config."volt.serverArgs"]
default = [""]
description = "LSP server arguments to pass when launching"

# [config."lspSettingArray"]
# default = []
# description = ""

# [config."lspSettingString"]
# default = ""
# description = ""

# [config."lspSettingBool"]
# default = false
# description = ""
