name = "csharp"
version = "1.0.1"
author = "sharpSteff"
display-name = "C#"
description = "C# for lapce using OmniSharp"
wasm = "target/wasm32-wasi/release/lapce-plugin-csharp.wasm"

[activation]
language = ["Csharp"]
workspace-contains = ["*/*.cs"]

[config."volt.serverPath"]
default = "OmniSharp"
description = "Path to custom LSP executable"

[config."volt.serverArgs"]
default = ["--languageserver"]
description = "LSP server arguments to pass when launching"

# [config."lspSettingArray"]
# default = []
# description = ""

# [config."lspSettingString"]
# default = ""
# description = ""

# [config."lspSettingBool"]
# default = false
# description = ""
