name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
         submodules: recursive
    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
    - name: Setup rust
      run: rustup target add wasm32-wasi
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build release
      run: cargo build -r
    - name: Publish plugin
      env:
         LAPCE_TOKEN: ${{ secrets.VOLTS_API_KEY }}
      run: volts --token $LAPCE_TOKEN && volts publish
