name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build release
      run: cargo build -r
    - name: Publish plugin
      env:
         LAPCE_TOKEN: ${{ secrets.VOLTS_API_KEY }}
      run: volts --token $LAPCE_TOKEN && volts publish
